import { VELUNE_SHOTS } from "@/components/velune/veluneStudy";

/** Final-picture requests over the unchanged Blender cut schedule. Never relabel the actual animatic. */
const V2_ACTIONS: Record<string, string> = {
  S01: "Use Image 8 for a tight, asymmetric chocolate opening. Large near folds frame a small EMPTY warm aperture. No person or dish. Let a restrained light change reveal fine chocolate texture; hold the camera. Override the guide's host and framing. Do not copy the final wide tunnel composition.",
  S02: "Use the pistachio carton in Image 1 alone. One short rigid turn, with a readable front, visible paperboard depth, fine paper grain and grounded contact. Keep the guide's edit, pivot and screen scale. Match the other two carton shots in size and position; do not mirror the printed lettering to match the reference angle. The photographed carton design from Image 1 remains attached to the turning box for EVERY frame, including the last frame before the next cut. Its whole-and-cut chocolate photograph, paper texture and plum setting must not revert to the Blender proxy.",
  S03: "Hard cut to the raspberry carton in Image 2 alone. Continue a small rigid turn at the same registered screen position and scale. Preserve the berry centre printed on its front, folds, paper texture and natural shadows. The Image 2 design stays on the carton throughout the turn and through the last frame of this shot. No inserted guide frame, simplified emblem, dissolve or flavour morph.",
  S04: "Hard cut to the caramel carton in Image 3 alone, at the same scale and position. For the ENTIRE 2.500–2.875s shot, keep Image 3's gold paperboard, photographic whole bonbon AND exposed caramel centre printed on the front, physical fold seams and plum setting. A short turn only, with the artwork rigidly attached to the box. This is one continuous finished-carton shot, not a reference still followed by a Blender render. Never replace its front with the guide's flat brown shield/V emblem or tan proxy background, even for a single frame. At 2.875s cut DIRECTLY from this same finished carton to S05; no intermediate proxy carton, extra cut, flying, opening or packaging deformation.",
  S05: "The low-centre tasting fork starts bare. Twelve bonbons matching the whole V-groove chocolates in Image 7 appear in the guide's order and form a readable question mark by approximately 3.792s. At about 3.875s chocolate bridges between them, closes the negative space and settles into a thick spread by the cut. Keep the fork registered. This is the one deliberate surreal merge, with rich chocolate material rather than explosive splashing.",
  S06: "Use ONLY the LEFT pistachio half from Image 6 for one already-cut chocolate half on the upright fork. Do not include the serving dish, raspberry or caramel in this shot. Keep the food and fork stable and the cut centre sharply readable. Two soft ivory-and-plum shoulders move behind it in the guide's opposing observer positions. Borrow wardrobe from Image 7, with faces outside the composition. Small working hand movement only; no new splitting, camera roll or portrait close-up.",
  S07: "Use Image 7 for the studio, working poses and whole chocolate form. Begin on five display bonbons stacked three left and two right. At about 6.833s move the camera BACKWARD through real depth to reveal the two workers. As their arms enter view, the left worker is already lifting a tasting utensil slightly toward chest height and the right worker continues one small open-hand indication toward the display. Add natural shoulder movement. Heads stay outside the crop. Display stacks remain fixed; no internal cut, added worker or digital zoom. The gestures override the guide's static performers.",
  S08: "Use Image 4 for one whole raspberry INGREDIENT already resting on the plum stage. A small stable turn reveals individual drupelets, fine hairs, natural unevenness and restrained highlights. It is a raspberry fruit, not ganache or a chocolate half. No falling entrance or rubber-like surface.",
  S09: "Hard cut to the already-open pistachio INGREDIENT in Image 5. Its dry cream shell, green kernel and purple skin rotate together as one stable assembly. Match the ingredient-stage light. It is a nut, not the chocolate half in Image 6. No opening explosion or drifting shell parts.",
  S10: "Use Image 6 to replace the guide's two-piece serving with EXACTLY THREE cut halves on one ivory dish: pistachio left, raspberry middle, caramel right. All exposed centres face the viewer. Preserve their contact, shell detail and contained filling. A slight unified dish turn only, with no plating, dripping or breaking action in this short shot.",
  S11: "Keep the guide's single report surface and three-second reading interval. Replace its proxy box illustrations with a clean three-column editorial layout: each flavour pairs the dimensional carton photographed in Images 1, 2 and 3 with its matching exposed chocolate centre from Image 6. These are printed photographs on ONE surface; cartons do not emerge or move independently. Small initial settling only. The exact The Centre Report graphic is a separate finishing asset, not an extra image slot; exact text will be composited afterward.",
  S12: "Use Image 9 for the WIDER chocolate passage and grounded dish in the lower left, with Image 6 controlling the three chocolate centres. No person in the aperture. The plate stays large enough to read, with room at right for Wonder within. added in post. Keep the dish grounded and the camera still. Begin at 13.083s with the warm luminous tunnel lighting of Image 9. From about 13.500–14.700s, smoothly lower the distant tunnel glow and broad environmental fill by roughly one stop, settling into deeper cocoa shadows. Keep a soft warm key on the three exposed centres and a restrained rim on the dish so every flavour remains readable. Hold the darker, warm final look from 14.700s through 15s. This is a slow change in the scene lighting; product position, framing, colour and focus stay stable. No flicker, pulsing or abrupt exposure step. This product payoff overrides the guide's host, tasting gesture and framing. It must be visibly different from Image 8 and the opening. No extra shot or fade to black.",
};

export const VELUNE_GENERATION_SHOTS = VELUNE_SHOTS.map((shot) => ({ ...shot, note: V2_ACTIONS[shot.id] }));
