export const shortOpening = "I built this studio to understand AI through making things. VELUNE taught me how much depends on the choices around the model: the references, the direction, what you keep and what you change. That connects to my workflow and enablement experience. I want to bring those strengths into a studio where I can make the work, help establish the standards, and make the process useful to the team.";

export const openingStory = [
  "The first film I made for VELUNE, the chocolate concept in my portfolio, had some beautiful moments. But when I watched it closely, the opening and ending felt too similar, and some of the packaging still looked artificial. I wanted it to hold up beyond the first impression.",
  "I went back to the references, refined the direction and reviewed the next take. Then I followed it into sound and the handoff. I wanted to understand why a result improved, and make those decisions easier to carry into the next brief.",
  "That is why I built the studio in my own time. With new models and connectors appearing, I want to get close enough to the tools to know what is useful, what still needs work, and what deserves another approach.",
  "It connects to what I already care about in my current role: understanding the friction that costs people time and building a better way through it. The work becomes more valuable when someone else can use what you have learned.",
  "This role brings those interests together. I want the responsibility of helping build the studio while making the work alongside the team. I would bring ownership of the problem, judgment about the approach, and care for what we put into the world. I want to help build a studio that can keep learning without losing its standards.",
];

export const storyPillars = [
  { name: "Ownership", point: "Stay with the problem through the handoff.", evidence: "You followed VELUNE from the generated picture into sound, playback and export choices. You also asked for all seven packshot views to move into Campaign Studio together, carrying the work forward as a set." },
  { name: "Judgment", point: "Choose the useful next step when the route is uncertain.", evidence: "You responded to provider failures, worked within H3's reference limit and deferred the Seedance toggle while improving the current film. You kept the camera guide and changed the appearance references where they were needed." },
  { name: "Taste", point: "Recognize where the work loses its intended effect.", evidence: "You noticed repeated bookends, artificial cartons, static characters and ingredient textures. You asked for a distinct opening, a product reveal and a controlled change of light at the end." },
];

export const strengths = [
  {
    title: "You see the small detail that changes whether work feels believable.",
    observation: "You spotted the repeated opening and closing composition, a Blender carton appearing between photographic frames, inactive studio characters, and artificial ingredient textures. You then asked for specific reference changes and a brighter-to-darker finish.",
    meaning: "That is a creative-review practice: noticing a defect, locating it in the cut, and giving an actionable note. It is much stronger evidence than saying you have an eye for detail.",
    line: "I review what the audience will actually experience. On VELUNE, I could point to the exact frame where the illusion broke and turn that into a specific change to the direction or references.",
    watch: "Bring one before-and-after example and a single sentence explaining the creative decision.",
  },
  {
    title: "You judge a tool from the next person's point of view.",
    observation: "You noticed that the VELUNE loader was easy to miss, that the old ice-cream link distracted from it, that audio controls were confusing, and that a bright surround made the film uncomfortable to watch. You wanted the finished film saved for the end of the case study.",
    meaning: "You think about attention, confidence and comprehension. For an internal studio, adoption depends on whether a colleague can understand the next step without the builder standing beside them.",
    line: "A tool can work technically and still ask too much of the person using it. I kept refining where people start, what they hear and what happens next, because that is part of making the capability usable.",
    watch: "Show the starting point and the handoff. Explain where a new user would have been confused and what you changed.",
  },
  {
    title: "You turn a one-off success into something repeatable.",
    observation: "You asked for model-specific example settings, correctly ordered references, reusable voice and effect prompts, six carton faces, and a way to take all seven rendered views into Campaign Studio together.",
    meaning: "You see the handoffs between tasks. You want the next run to retain the decisions that made the previous one work. That is directly relevant to a studio that must scale beyond one expert.",
    line: "Once a result works, my next question is how someone else repeats it. I want the right references, settings and handoff to travel together, so people can spend their attention on the creative decision.",
    watch: "Show how the reference set, settings and rendered views travel together. If someone else has tried it, bring their actual feedback.",
  },
  {
    title: "You learn by narrowing the problem, and you know when to sequence the work.",
    observation: "When reference requests failed, you brought the provider's exact errors and support response into the conversation. You moved the immediate VELUNE attempt to H3 Max, worked within the nine-image limit, and explicitly deferred the Seedance toggle until the current film was working.",
    meaning: "Your learning has a practical feedback loop: attempt, observe, diagnose, change and review. The choice to defer another model also shows scope judgment, not just enthusiasm for new tools.",
    line: "I learn through the failure as well as the output. I try to identify whether the problem is the reference, the prompt, the model or the interface, then change the layer that is causing it.",
    watch: "Prepare the exact problem, what you chose to test next, and why you deferred the other model. Explain the AI assistance used.",
  },
  {
    title: "You keep going past the impressive preview.",
    observation: "You followed the film into voiceover, original sound playback, soundtrack mixing, download handoffs, complete packaging panels and the way the work would be presented to a hiring manager. A generated video was not the end of your questions.",
    meaning: "You are attentive to the final steps that make work useful and understandable. That instinct connects your operational background to a role that must actually deliver content.",
    line: "I care about the point where an experiment becomes usable work: the sound, the export, the source files, the review and the handoff. I want the person receiving it to know what they have and what still needs a decision.",
    watch: "Show the sound and handoff choices, then identify the final review or delivery steps for the asset in front of you.",
  },
];

export const roleMap = [
  ["Personally produce stills, motion and video", "VELUNE, its visual references and supplied H3 film; the ice-cream motion study; packshot and campaign tools.", "Show the finished result and explain what you personally directed, tested and refined. Be ready to describe the editing and finishing steps that still need a traditional editor."],
  ["Stand up tools, intake, standards and quality gates", "Your résumé describes internal platform ownership, intake-to-deployment stages, role-based access and enterprise review. Project Forge is the public case study.", "Explain one actual production problem, the operating decision you made, and what changed for the people doing the work."],
  ["Lead a lean team while staying hands-on", "Your résumé states a team of eight with three direct reports, alongside hands-on build work.", "Bring one coaching example and one example of setting priorities or resolving disagreement. The portfolio cannot demonstrate these on its own."],
  ["Teach and operationalize AI", "The résumé describes your Enterprise Champion role and AI literacy program. The studio contains reusable prompts, examples and a playbook.", "Prepare a real learner's starting point, what you taught, how you checked understanding, and what they could do independently afterwards."],
  ["Make build-vs-buy and vendor decisions", "The studio shows model routing and your response to provider constraints. The build-vs-buy page documents your thinking.", "Explain total delivery effort, rights, reliability and maintenance. Do not equate the cheapest generation with the cheapest approved asset."],
  ["Measure quality, speed, adoption and in-house volume", "Your résumé describes reduced manual effort and returned capacity. This conversation supplies examples of iteration, not a controlled business benchmark.", "Bring a defensible baseline or propose how to establish one. Separate measured results from observations and goals."],
];

export const walkthrough = [
  { time: "0:00–0:45", title: "Frame the visit", href: "/", link: "Portfolio home", show: "Open with the purpose, not the navigation. Explain that the portfolio contains work you made and a studio you built to make that work.", say: "I'll show one creative example, the workflow behind it, and where my operational experience would help make that repeatable for a team." },
  { time: "0:45–2:00", title: "Set up VELUNE", href: "/velune", link: "VELUNE case study", show: "Introduce the fictional chocolate brief and the intended feeling: curiosity leading to discovery. Show the new carton imagery and one ingredient or serving reference. State your role and the AI assistance used.", say: "The brief gave me a way to test product consistency, short-form storytelling and how a camera plan survives a generative pass." },
  { time: "2:00–3:30", title: "Show one decision that improved the work", href: "/velune", link: "Reference and process story", show: "Use the carton that briefly reverted to the Blender proxy, or the opening that resembled the ending. Explain the symptom, the diagnosis, the changed instruction or reference, and the visible result. If showing failure, keep it to one prepared comparison.", say: "This was the point where the tool's output needed a production decision. I changed what controlled appearance while keeping the camera plan useful." },
  { time: "3:30–4:15", title: "Let the film resolve the story", href: "/velune#velune-film", link: "Finished VELUNE film", show: "Play the 15-second film once, with the intended original sound and voiceover combination checked beforehand. Stop talking while it plays. Leave two seconds of quiet afterwards.", say: "That is the current portfolio result. The main improvement was greater continuity between the product references and the finished frames." },
  { time: "4:15–6:00", title: "Show how the next person can repeat it", href: "/ai-studio/packshots?mode=artwork", link: "Prepare Packshot Studio", show: "Before the interview, open artwork mode, load the VELUNE example and render the seven views locally. Keep that tab open. During the walkthrough, switch to it to show the six faces, rendered views and whole-set handoff to Campaign Studio. Reopening the page starts without the in-memory render set.", say: "This is the part I would want a colleague to inherit: the context travels with the assets, and they can still make their own creative choices." },
  { time: "6:00–7:15", title: "Connect it to production you already lead", href: "/project-forge", link: "Project Forge case study", show: "Use the public Project Forge case study to explain your internal workflow experience. Talk through intake, review and release at the level appropriate for the room. Keep confidential names, screenshots and live records out of a public demonstration.", say: "This is where I have deeper operating experience. I know that a useful tool needs ownership, clear handoffs and review points, because I have had to make that work inside the Agency." },
  { time: "7:15–8:00", title: "Invite a production question", href: "/ai-studio/playbook", link: "Production playbook", show: "Close the demo and return attention to the panel. Open the playbook only if they want the detail. Bring the conversation back to their actual content demand.", say: "Where would a workflow like this need to prove itself first in your production mix?" },
];

export const stories = [
  { title: "Removing friction for people", source: "Résumé + your letter to Nan", situation: "Badge requests moved through coordination, scheduling, readiness checks, build and review. Your résumé describes work spanning several roles.", action: "Explain the intake-to-deployment workflow you owned, who you involved in defining it, and one decision about readiness or approval that removed repeated chasing.", result: "Use your supported observation about returned capacity. Add a measured turnaround or rework figure only if you have the baseline and comparison.", lesson: "The human payoff belongs at the centre: colleagues gained space to focus on higher-value work. Supply one real person or team example without inventing a quote.", prepare: "Name one difficult tradeoff, one stakeholder who challenged the approach, and what you changed after listening." },
  { title: "Turning a visual failure into better direction", source: "Observed VELUNE iteration", situation: "The generated film reused similar framing at the opening and ending, and some carton or ingredient shots retained an artificial look.", action: "You identified the shot-level problems, supplied better individual references, clarified which source controlled appearance, and kept the working camera guide while changing the relevant direction.", result: "You reported that the later execution was much better, then gave two further notes about carton continuity and closing light. Show the actual versions if you have them; don't imply every defect disappeared.", lesson: "Tool fluency includes recognizing when another reference or a targeted correction is more useful than a longer prompt.", prepare: "Be able to explain why you kept the Blender guide and why a different opening reference helped the narrative." },
  { title: "Making expertise transferable", source: "Observed studio UX decisions", situation: "The tool could render seven package views, but its individual buttons encouraged a fragmented handoff. The example loader and sound workflow also required explanation.", action: "You asked for a whole-set transfer, a prominent starting point, complete example settings and clearer audio finishing. Describe the intended user and the confusion you were solving.", result: "Those paths were implemented and checked. We have not measured colleague adoption or task-completion time.", lesson: "A capability starts to scale when another person can carry the context forward and make the next decision.", prepare: "Before the interview, ask one colleague to try an authorized demo path without coaching. Treat any finding as a small usability observation, not a broad adoption claim." },
  { title: "Teaching and leading through uncertainty", source: "Résumé; complete with your real example", situation: "Choose one actual AI literacy session, coaching conversation or team change. The attached résumé establishes the role, but does not give the full event.", action: "Explain how you learned the person's starting point, made the tool relevant to their task, and let them practise. Describe how you handled an objection or mistake.", result: "State what they could do afterwards and how you know. Attendance alone is not evidence of capability.", lesson: "Leadership is helping someone become more capable while protecting their confidence and the team's quality standards.", prepare: "Fill in the date, your contribution, the learner's task, the obstacle and one observable outcome. Do not rehearse a hypothetical as a past event." },
];

export const questions = [
  { question: "Why do you want to move from CRM and AI enablement into this role?", listenFor: "Use one concrete VELUNE moment to show your judgment, then connect it to your workflow and enablement experience. Close with the responsibility you want to take alongside the team. If asked for a career summary, give your current role and scope first." },
  { question: "This is a hands-on production role. What did you personally make?", listenFor: "Show one finished result. Separate your concept, direction, testing and refinement from AI-generated media, AI-assisted code and any outside work. Explain the tools and final delivery steps you actually used." },
  { question: "How would you address your limited traditional studio experience?", listenFor: "Name the gap once. Show existing operational and leadership evidence, explain your current craft work, then describe how you would develop the missing depth while staying accountable for quality." },
  { question: "Why should we choose you over an experienced studio director?", listenFor: "Speak about your combination of internal workflow knowledge, hands-on learning and team enablement. Respect other candidates' craft. Do not claim superiority you cannot substantiate." },
  { question: "Tell me about a generation that failed and what you changed.", listenFor: "Use a specific VELUNE shot. Distinguish a provider input failure from a creative quality issue. Explain the smallest useful change and the actual outcome." },
  { question: "How would you respond to a creative lead who thinks AI lowers quality?", listenFor: "Ask what quality means for their work, acknowledge the concern, propose a bounded comparison, and be willing to retain the traditional method if the result does not meet the bar." },
  { question: "How do you lead people whose craft skills are deeper than yours?", listenFor: "Describe clear ownership, listening, critique against the brief, and where you defer to specialist judgment. Bring an actual leadership example, not only a philosophy." },
  { question: "What would you build, what would you buy, and what would you keep with vendors?", listenFor: "Compare quality, rights, time, repeatability, total cost and maintenance. A custom prototype is not automatically the enterprise answer. Vendors can remain the right production partner." },
  { question: "How would you measure the studio in its first 90 days?", listenFor: "Establish a baseline, then track approved assets, elapsed delivery time, human finishing effort, repeatability and adoption. Include retries and review cost. Present targets as agreed goals, not past results." },
  { question: "Tell me about a colleague you helped become more capable with AI.", listenFor: "Name a real teaching moment, the task before and after, your adaptation to the learner, and how you verified independence. No invented outcome." },
  { question: "How do you keep rights, privacy and brand approvals in the workflow?", listenFor: "Use approved tools and appropriate sources, preserve provenance, define accountable human review, and stop when approval or rights are unresolved. An AI observation is not authorization." },
  { question: "How would you handle a launch deadline when the AI route is still inconsistent?", listenFor: "Protect the deliverable. Define a cutoff for experimentation, use a proven fallback, communicate the tradeoff early and capture the learning after delivery." },
];

export const objections = [
  { title: "How does your background prepare you to lead a creative production studio?", answer: "My established experience is in production workflows, marketing technology and leading people inside the business. I've been extending that into hands-on visual production, which is why I built the studio and made work with it. I would bring that operating experience, stay personally active in making the work, and develop the craft areas where this team has greater depth. The creative standard still has to be met, and I can show how I review and improve the work against a brief.", follow: "The JD's ten-year requirement includes creative technology and related fields, not only traditional studio work. Explain your actual chronology and transferable experience accurately, alongside the specific craft depth you are still developing." },
  { title: "Is this a software portfolio or a creative-production portfolio?", answer: "The studio is one part of the evidence. Let me show the film first, then the decisions that improved it. The tooling matters because it helps carry those decisions into the next brief, but the output still has to work visually and emotionally.", follow: "Use one finished piece and one targeted comparison. Be ready to discuss composition, pacing, materials, sound and finish without returning immediately to APIs." },
  { title: "Did you build this yourself, or did AI do it?", answer: "I built it with AI assistance. I set the direction, chose the workflows, reviewed the outputs and drove the iterations; AI helped with implementation and media generation. I can walk through a decision, the failure it addressed and how we checked the change. I take responsibility for what I present, while being clear about the assistance used.", follow: "Adapt the ownership description to the specific asset. Do not imply unaided coding, manual modelling or editing that you did not do." },
  { title: "How would you lead established creatives?", answer: "I would start by understanding the quality bar they already hold and where production gets in their way. I'd make responsibilities explicit, invite critique early and keep doing work myself. My job would be to create conditions for excellent work and make useful decisions with the team. When a specialist has deeper judgment in a craft area, I want that judgment in the process.", follow: "Add a real example of listening and changing your mind. Respect is more convincing as a behavior than as a promise." },
  { title: "Why not just buy a suite or use an existing vendor?", answer: "We should, where it is the better route. Building this prototype helped me understand the control points and failure modes. For the Agency I'd compare an existing suite, direct tools, vendors and a small amount of custom integration against a real recurring brief. I'd include review effort, maintenance, rights and reliability in the decision.", follow: "Name one thing you would deliberately avoid building. For example, don't create a custom editor before proving that an existing one cannot meet the requirement." },
  { title: "What would you do if the work is not good enough?", answer: "I would name the specific quality problem, decide whether a targeted change can fix it within the deadline, and keep a proven finishing or production route available. A failed experiment can still inform the workflow, but it cannot be passed off as an approved deliverable. I would own that decision and communicate it early.", follow: "Do not promise that more prompting always solves the problem. Sometimes the right decision is a reshoot, conventional edit, specialist support or a different concept." },
];

export const phases = [
  { period: "Days 1–30", title: "Learn the demand. Make real work.", actions: ["Agree two recurring pilot briefs with the Head of Production and creative partners. Ask where work queues, repeats or needs too much adaptation.", "Personally produce a baseline set using approved tools. Sit with reviewers and document why assets pass or fail.", "Map current ownership, source rights, review steps and vendor dependencies. Identify existing capabilities before proposing new software."], deliverable: "Two bounded pilots, a shared quality rubric, baseline delivery effort and a clear list of work the studio is not ready to absorb." },
  { period: "Days 31–60", title: "Prove the workflow beyond yourself.", actions: ["Have a second operator reproduce one pilot from the documented intake and references. Observe where they need help.", "Teach through a live brief, with a small template and a review exercise. Update the playbook from the learner's questions.", "Compare the AI route with the current route, including retries, human finishing, review and exceptions. Make a build-vs-buy recommendation from that evidence."], deliverable: "A repeatable workflow, one independently completed run, an evidence-based tooling decision and a short failure log with owners." },
  { period: "Days 61–90", title: "Scale what has earned it.", actions: ["Expand the successful pilot to a controlled set of additional briefs or adaptations. Keep a defined exception path and accountable sign-off.", "Review capacity with the team and Head of Production. Bring work in-house where quality, rights, speed and cost support the move.", "Report what improved, what stayed manual and what failed. Agree the next investment rather than treating every new model as an adoption priority."], deliverable: "A small, reliable service with a clear intake, quality threshold, ownership model and measured case for its next stage." },
];

export const audienceQuestions = [
  { when: "Before the walkthrough", ask: "Would it be most useful to start with the finished work, the production workflow, or how I'd stand up the team?", purpose: "Offer a choice, then follow it. If they have a set agenda, let their questions lead." },
  { when: "After showing a specific decision", ask: "Is consistency, finishing time or volume the more difficult constraint in your current mix?", purpose: "Connect the evidence to a real production need. Use their answer to decide which example deserves more time." },
  { when: "When discussing partnership", ask: "What would you most want this Director to take ownership of alongside the Head of Production?", purpose: "Clarify the actual leadership relationship and expectations. Don't assume the operating model is already settled." },
  { when: "When discussing adoption", ask: "Where are teams already experimenting successfully, and where are they still hesitant?", purpose: "Recognize work already happening. Position yourself as someone who learns from colleagues and connects efforts." },
  { when: "Near the end", ask: "Six months in, what would make you say the studio is doing useful work?", purpose: "Surface how they define success before you prescribe a dashboard or a headcount plan." },
  { when: "Before closing, if time allows", ask: "Is there an area of my experience you'd like me to give a more concrete example of?", purpose: "Invite clarification without forcing the panel to make a hiring judgment in the room." },
];
