"use client";

import { useEffect, useRef, useState } from "react";
import { TILE_BOX, isMotion, type ShowcaseItem } from "@/lib/showcase";

/**
 * Motion plays only while it is on screen, and only if the reader has not
 * asked for less of it. Four clips autoplaying above the fold on a phone is
 * a way to make a portfolio feel expensive to look at.
 */
function Motion({ item }: { item: ShowcaseItem }) {
  const ref = useRef<HTMLVideoElement>(null);
  const [reduced, setReduced] = useState(false);

  useEffect(() => {
    const q = window.matchMedia("(prefers-reduced-motion: reduce)");
    setReduced(q.matches);
    const on = () => setReduced(q.matches);
    q.addEventListener("change", on);
    return () => q.removeEventListener("change", on);
  }, []);

  useEffect(() => {
    const el = ref.current;
    if (!el || reduced) return;
    const io = new IntersectionObserver(
      ([e]) => {
        if (e.isIntersecting) void el.play().catch(() => {});
        else el.pause();
      },
      { threshold: 0.35 },
    );
    io.observe(el);
    return () => io.disconnect();
  }, [reduced]);

  return (
    <video
      ref={ref}
      src={item.file}
      poster={item.poster}
      muted
      loop
      playsInline
      preload="metadata"
      // Reduced motion still gets the poster frame and a working control.
      controls={reduced}
      className="absolute inset-0 h-full w-full object-cover"
    />
  );
}

/**
 * The output strip. Craft first, argument second.
 *
 * Rendered only when there is real work to show — `page.tsx` filters the
 * manifest against the filesystem at build time, so an empty showcase is an
 * absent section rather than a row of broken images in front of a recruiter.
 */
export function ShowcaseStrip({ items }: { items: ShowcaseItem[] }) {
  if (items.length === 0) return null;

  return (
    <section
      aria-label="Selected output"
      className="mx-auto max-w-[1440px] px-6 pb-4 sm:px-12 lg:px-24"
    >
      <div className="flex flex-wrap items-baseline justify-between gap-x-8 gap-y-2">
        <span className="label !tracking-[0.16em]">Made with the studio</span>
        <span className="text-xs text-muted/80">
          Every frame below was generated by the pipeline on this site.
        </span>
      </div>

      <ul className="mt-6 grid grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-4">
        {items.map((item) => (
          <li key={item.id} className="group">
            <div
              className={`relative overflow-hidden rounded-[6px] border border-border-soft bg-surface-2 ${TILE_BOX}`}
            >
              {isMotion(item.file) ? (
                <Motion item={item} />
              ) : (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={item.file}
                  alt={item.title}
                  loading="lazy"
                  className="absolute inset-0 h-full w-full object-cover"
                />
              )}
            </div>
            <p className="mt-2.5 text-sm font-semibold leading-snug">{item.title}</p>
            <p className="mt-1 text-xs leading-[1.55] text-muted">{item.note}</p>
            <p className="mt-1.5 font-mono text-[10px] uppercase tracking-[0.1em] text-muted/70">
              {item.model}
              {item.cost ? ` · ${item.cost}` : ""}
            </p>
          </li>
        ))}
      </ul>
    </section>
  );
}
